### ISSUE TITLE
Configure sbt-release

### ISSUE THREAD

**Issue by joprice** [tptodorov/sbt-cloudformation#16]
After adding sbt-test in my other pr, I noticed that I was getting warnings about overwriting ivy versions and found that the version was set to  `SNAPSHOT`. Configuring sbt-release will give more structure to the release process and avoid states like this. It also creates tags (I can see that there are a few missing atm).

**Comment by tptodorov** [comment]
yes, i use sbt-release in other projects, but was lazy here. will do went i am back.

**Comment by tptodorov** [comment]
Fixed with 93c9e331a2d2341489544b5129f53f5939c3d1e1
