### ISSUE TITLE
Could you cut a new release?

### ISSUE THREAD

**Issue by myyk** [tptodorov/sbt-cloudformation#7]
I had thought the last release included 3d67605f045228be8b856e934d5cfef616e3a277 but it seems I was mistaken since locally I was using a version I published as 0.3.0.

I tested locally publishing master as 0.3.1-SNAPSHOT and found the behavior to be different from 0.3.0.

This can easily be tested with a project that uses sbt-cloudformation while your ~/.aws/credentials are moved somewhere else. The project fails under 0.3.0, but not with a build from master. Maybe make sure to `sbt clean-files` before releasing.

**Comment by tptodorov** [comment]
I've released 0.4.0 which includes your patch.

**Comment by myyk** [comment]
Hi sorry, to bother you again, but it doesn't look like 0.4.0 is actually released. 

http://dl.bintray.com/sbt/sbt-plugin-releases/com.github.tptodorov/sbt-cloudformation/scala_2.10/sbt_0.13/

**Comment by tptodorov** [comment]
Hi, just came back from vacation. Try again, should be there now.
